"""
Run this script once to generate sample .docx files in the sample_data/ folder.
These files can be uploaded via the API or Django admin to test the system.

Usage: python create_sample_docs.py
"""

from docx import Document


def create_doc(filename: str, title: str, paragraphs: list[str]) -> None:
    doc = Document()
    doc.add_heading(title, level=1)
    for para in paragraphs:
        doc.add_paragraph(para)
    doc.save(filename)
    print(f"Created: {filename}")


if __name__ == "__main__":
    # --- Sample 1: Python Programming ---
    create_doc(
        "sample_data/python_intro.docx",
        "Introduction to Python Programming",
        [
            "Python is a high-level, interpreted programming language created by Guido van Rossum "
            "and first released in 1991. Python's design philosophy emphasizes code readability, "
            "and its syntax allows programmers to express concepts in fewer lines of code than "
            "languages like C++ or Java.",

            "Python supports multiple programming paradigms, including structured, object-oriented, "
            "and functional programming. It has a large and comprehensive standard library, often "
            "described as coming with 'batteries included'.",

            "Python is dynamically typed and garbage-collected. It uses indentation (whitespace) "
            "to delimit code blocks rather than curly braces or keywords, which enforces a clean "
            "and consistent code style.",

            "Python is widely used in web development (Django, Flask), data science (pandas, NumPy), "
            "machine learning (TensorFlow, PyTorch), automation, and scripting. It is consistently "
            "ranked as one of the most popular programming languages in the world.",

            "Key features of Python include: easy syntax similar to English, interpreted execution "
            "(no compilation needed), extensive standard library, cross-platform compatibility, "
            "strong community support, and excellent integration with other languages and tools.",

            "To install Python, visit python.org and download the latest stable version. "
            "Most Linux and macOS systems come with Python pre-installed. On Windows, you can also "
            "install Python via the Microsoft Store or using a package manager like Chocolatey.",

            "Virtual environments in Python allow you to create isolated environments for different "
            "projects. This means each project can have its own dependencies without conflicts. "
            "Use 'python -m venv env' to create a virtual environment and 'source env/bin/activate' "
            "(on Unix) or 'env\\Scripts\\activate' (on Windows) to activate it.",

            "Package management in Python is handled by pip, the Python package installer. "
            "Common commands: 'pip install package_name' to install, 'pip freeze > requirements.txt' "
            "to save dependencies, and 'pip install -r requirements.txt' to install from a file.",
        ]
    )

    # --- Sample 2: Docker & Containers ---
    create_doc(
        "sample_data/docker_guide.docx",
        "Docker and Containerization Guide",
        [
            "Docker is an open-source platform that automates the deployment of applications inside "
            "lightweight, portable containers. Containers package an application with all its "
            "dependencies, ensuring it runs consistently across different computing environments.",

            "A Docker container is a runnable instance of a Docker image. Images are read-only "
            "templates used to create containers. Images are built from a Dockerfile, which is a "
            "text file containing instructions for assembling the image layer by layer.",

            "Key Docker concepts: "
            "Image — a read-only template with instructions for creating a container. "
            "Container — a runnable instance of an image. "
            "Dockerfile — a text file with build instructions. "
            "Registry — a storage and distribution system for Docker images (e.g., Docker Hub). "
            "Volume — a mechanism for persisting data generated by containers.",

            "Docker Compose is a tool for defining and running multi-container Docker applications. "
            "With a single docker-compose.yml file you define services, networks, and volumes. "
            "Running 'docker-compose up' starts all services defined in the file.",

            "A basic Dockerfile example:\n"
            "FROM python:3.11-slim\n"
            "WORKDIR /app\n"
            "COPY requirements.txt .\n"
            "RUN pip install -r requirements.txt\n"
            "COPY . .\n"
            "CMD [\"python\", \"manage.py\", \"runserver\", \"0.0.0.0:8000\"]",

            "Docker volumes are the preferred mechanism for persisting data generated by Docker "
            "containers. Unlike bind mounts, volumes are managed by Docker and can be shared safely "
            "among multiple containers. Use 'docker volume create' to create a named volume.",

            "Container networking: Docker creates a default bridge network for containers. "
            "Containers on the same network can communicate using their service name as a hostname. "
            "In docker-compose, services can reference each other by name (e.g., 'db' for a "
            "database service).",

            "Best practices for Docker: use specific version tags instead of 'latest', minimize "
            "image size with multi-stage builds, never store secrets in images, use .dockerignore "
            "to exclude unnecessary files, and run containers as non-root users in production.",
        ]
    )

    print("\nSample files created in sample_data/. Upload them via the API or Django Admin.")
